# Generated by Django 4.2.9 on 2024-02-19 03:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=10, null=True, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=20, null=True)),
                ('is_store', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(max_length=20)),
                ('storeTel', models.CharField(max_length=20)),
                ('storeDescription', models.CharField(max_length=20)),
                ('storeThumbnail', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='StoreSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tinting', models.BooleanField(default=False)),
                ('wraping', models.BooleanField(default=False)),
                ('ppf', models.BooleanField(default=False)),
                ('carwash', models.BooleanField(default=False)),
                ('gloss', models.BooleanField(default=False)),
                ('detail_carwash', models.BooleanField(default=False)),
                ('car_repair', models.BooleanField(default=False)),
                ('painting', models.BooleanField(default=False)),
                ('autoglass', models.BooleanField(default=False)),
                ('tire', models.BooleanField(default=False)),
                ('store', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='account.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeimage', models.ImageField(upload_to='')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='account.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('zonecode', models.CharField(max_length=10)),
                ('jibunAddress', models.CharField(max_length=100)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='account.store')),
            ],
        ),
    ]
