# Generated by Django 4.2.9 on 2024-02-07 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='storenTel',
            new_name='storeTel',
        ),
    ]
