# Generated by Django 5.0.2 on 2024-02-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='zonecode',
            field=models.CharField(max_length=6),
        ),
    ]
