# Generated by Django 4.2.9 on 2024-02-19 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storeaddress',
            table='StoreAddress',
        ),
        migrations.AlterModelTable(
            name='storeimage',
            table='StoreImage',
        ),
        migrations.AlterModelTable(
            name='storeskill',
            table='StoreSkill',
        ),
    ]
